---
# Use this command to deploy
# kubectl create -f LetsEncrypt-prod.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-dns
spec:
  acme:
    email: postmaster@greenpeace.org
    privateKeySecretRef:
      name: letsencrypt-dns-staging
    server: "https://acme-staging-v02.api.letsencrypt.org/directory"
    solvers:
      - dns01:
          cloudDNS:
            project: global-it-infrastructure
            serviceAccountSecretRef:
              key: global-it-infrastructure.json
              name: clouddns-dns01-solver-svc-acct
