---
apiVersion: v1
kind: Secret
metadata:
  name: vault-issuer-token
  namespace: cert-manager
  annotations:
    kubernetes.io/service-account.name: "cert-manager-vault"
type: kubernetes.io/service-account-token
data: {}
